name: Build Eden Nightly
concurrency:
  group: build-eden-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

jobs:
  windows:
    runs-on: windows-latest
    name: "Windows (${{ matrix.target }})"
    strategy:
      matrix:
        include:
           - target: x86_64
             qt_arch_target: win64_msvc2022_64
             qt_arch_version: 6.9.0
    env:
      TARGET: ${{ matrix.target }}
      ARCH: ${{ matrix.target }}
      OS: windows
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros

    steps:
      - name: Clone eden-mirror
        uses: actions/checkout@v4
        with:
          repository: Vee99BR/eden-mirror
          submodules: recursive
          fetch-depth: 0

      - name: Restore vcpkg cache
        uses: actions/cache/restore@v4
        id: vcpkg-cache
        with:
          path: |
            ${{ github.workspace }}/build/vcpkg_installed
            ${{ github.workspace }}/build/externals
            ${{ github.workspace }}/vcpkg_installed
            ${{ github.workspace }}/.vcpkg
          key: cache-vcpkg-${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: cache-vcpkg-

      - name: Restore ccache cache
        uses: actions/cache/restore@v4
        id: ccache-cache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: cache-ccache-${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: cache-ccache-

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.target }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_arch_version }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ matrix.qt_arch_target }}
          modules: qtmultimedia qt5compat
          cache: true
          add-tools-to-path: true

      - name: Install Vulkan SDK
        shell: pwsh
        run: |
          sed -i -E 's#^\$ExeFile = ".*"#\$ExeFile = "vulkansdk-windows-X64-\$VulkanSDKVer.exe"#' .ci/windows/install-vulkan-sdk.ps1
          .\.ci\windows\install-vulkan-sdk.ps1

      - name: Build Eden!
        shell: bash
        run: DEVEL=true WINDEPLOYQT="$QT_ROOT_DIR/bin/windeployqt6.exe" CCACHE=true .ci/windows/build.sh -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR/lib/cmake/Qt6

      - name: Pack Eden!
        shell: bash
        run: ./.ci/windows/package.sh

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eden-windows-${{ matrix.target }}.zip
          path: artifacts/*

      # See <https://github.com/actions/cache/commit/c74ca4022c9c3055a63985d9a25f9a7cc1ffc5d2>
      - name: Always Save vcpkg Cache
        id: vcpkg-cache-save
        if: always() && steps.vcpkg-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.vcpkg-cache.outputs.cache-primary-key }}
          path: |
            ${{ github.workspace }}/build/vcpkg_installed
            ${{ github.workspace }}/build/externals
            ${{ github.workspace }}/.vcpkg

      - name: Always Save ccache Cache
        id: ccache-cache-save
        if: always() && steps.ccache-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.ccache-cache.outputs.cache-primary-key }}
          path: ${{ env.CCACHE_DIR }}
