name: Build Eden Nightly
concurrency:
  group: build-eden-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

jobs:
  windows:
    runs-on: windows-latest
    name: "Windows (${{ matrix.target }})"
    strategy:
      matrix:
        include:
           - target: x86_64
             qt_arch_target: win64_msvc2022_64
             qt_arch_path: msvc2022_64
             qt_arch_version: 6.9.0
    env:
      TARGET: ${{ matrix.target }}
      ARCH: x86_64
      OS: windows
      CCACHE_DIR: ${{ github.workspace }}/.cache/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Vee99BR/eden-mirror
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Set up vcpkg cache
        uses: actions/cache@v4
        id: vcpkg-cache
        with:
          path: |
            ${{ github.workspace }}/build/vcpkg_installed
            ${{ github.workspace }}/build/externals
            ${{ github.workspace }}/.vcpkg
          key: ${{ runner.os }}-${{ matrix.target }}-vcpkg-${{ hashFiles('**/CMakeLists.txt', '**/vcpkg.json') }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-${{ matrix.target }}-vcpkg-

      - name: Set up ccache cache
        uses: actions/cache@v4
        id: ccache-cache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.target }}-ccache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.target }}-ccache-

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.target }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_arch_version }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ matrix.qt_arch_target }}
          modules: qtmultimedia qt5compat
          cache: true

      - name: Install Vulkan SDK
        shell: pwsh
        run: |
          sed -i -E 's#^\$ExeFile = ".*"#\$ExeFile = "vulkansdk-windows-X64-\$VulkanSDKVer.exe"#' .ci/windows/install-vulkan-sdk.ps1
          .\.ci\windows\install-vulkan-sdk.ps1

      - name: Store Version on ENV and Set Qt env vars
        shell: bash
        env:
          QT_ARCH_VERSION: ${{ matrix.qt_arch_version }}
          QT_ARCH_PATH: ${{ matrix.qt_arch_path }}
        run: |
          QTDIR="/c/Qt/${QT_ARCH_VERSION}/${QT_ARCH_PATH}"
          echo "VERSION=$(git rev-list --count HEAD)" >> "$GITHUB_ENV"
          echo "QTDIR=$QTDIR" >> "$GITHUB_ENV"
          echo "QT_ROOT_DIR=$QTDIR" >> "$GITHUB_ENV"
          echo "QT_PLUGIN_PATH=$QTDIR/plugins" >> "$GITHUB_ENV"
          echo "QML2_IMPORT_PATH=$QTDIR/qml" >> "$GITHUB_ENV"
          echo "PATH=$QTDIR/bin:$PATH" >> "$GITHUB_ENV"

      - name: Build Eden!
        shell: bash
        run: DEVEL=true WINDEPLOYQT="$QTDIR/bin/windeployqt6.exe" CCACHE=true .ci/windows/build.sh -DCMAKE_PREFIX_PATH=$QTDIR/lib/cmake/Qt6

      - name: Pack Eden!
        shell: bash
        run: ./.ci/windows/package.sh

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eden-windows-${{ matrix.target }}.zip
          path: artifacts/*