name: "[B]uild a Mirror of Eden"
concurrency:
  group: build-eden-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

jobs:
  windows:
    runs-on: windows-latest
    name: "Windows (${{ matrix.target }})"
    strategy:
      matrix:
        include:
           - target: x86_64
             qt_arch_target: win64_msvc2022_64
             qt_arch_version: 6.10.0
    env:
      TARGET: ${{ matrix.target }}
      ARCH: ${{ matrix.target }}
      OS: windows
      SCCACHE_GHA_ENABLED: "true"

    steps:
      - name: Clone eden-mirror
        uses: actions/checkout@v4
        with:
          repository: Vee99BR/eden-mirror
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git identity
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Cherry-pick fixes
        shell: bash
        run: |
          # package.sh: Improve package.sh using temp dir
          git cherry-pick 8a5274a428220c4878755fdb42d6b9551d3a86a8
          # externals: sirit: Fix usage of USE_CCACHE
          git cherry-pick 4b3ddf7b2f4833e9d310acf83297052108645f24
          # .ci: install-vulkan-sdk.ps1: Fix versioning after 1.4.313.0
          git cherry-pick cb7639952f7feb78161e514e5b26b71298f95460

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.target }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_arch_version }}
          host: 'windows'
          target: 'desktop'
          arch: ${{ matrix.qt_arch_target }}
          modules: qtmultimedia qt5compat
          cache: true
          add-tools-to-path: true

      - name: Install Vulkan SDK
        shell: pwsh
        run: .\.ci\windows\install-vulkan-sdk.ps1

      - name: Build Eden!
        shell: bash
        run: WINDEPLOYQT="$QT_ROOT_DIR/bin/windeployqt6.exe" .ci/windows/build.sh -DCMAKE_PREFIX_PATH="$QT_ROOT_DIR/lib/cmake/Qt6" -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DUSE_CCACHE=ON -DYUZU_USE_BUNDLED_QT=OFF -DCMAKE_SYSTEM_PROCESSOR="${{ matrix.target }}"

      - name: Pack Eden!
        shell: bash
        run: ./.ci/windows/package.sh

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eden-windows-${{ matrix.target }}.zip
          path: artifacts/*
